### ISSUE TITLE
Can you use this separate from Unreal Engine 4 build? Is it allowed by license?

### ISSUE THREAD

**Issue by SasisaDev** [allcoolthingsatoneplace/UnrealPakTool#2]
Can someone use this tool separate from UE4 to work with pak files, as example, to make content mods?

**Comment by betweeentwoworlds** [comment]
i think as long as you are contributing to unreal engine community... its ok, and as for license there can be only profit limits..

**Comment by allcoolthingsatoneplace** [comment]
License - [https://www.unrealengine.com/en-US/eula/publishing](License)

> You are permitted to post snippets of Engine Code, up to 30 lines of code in length, online in public forums for the sole purpose of discussing the content of the snippet, or distribute such snippets in connection with supporting patches and plug-ins for the Licensed Technology, so long as it is not for the purpose of enabling non-Engine Licensees to use or modify any Engine Code, or to aggregate, recombine, or reconstruct any larger portion of the Engine Code.

so as long u don't rewrite this thing* for ur own purposes, u just want to modify with part of this thing* some game resources that runs on UE u can do it, and second thing those game resources are distributed by publishers and they have their own rules so when u modifying game files u violate game publisher rules not epics.
so while u doing something in context of epic games eco system u are good to go.
* - unreal engine
